language: cpp
compiler:
  - gcc
notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required

addons:
  apt:
    packages:
      - cmake
      - qt5-default
      - libprotobuf-dev
      - protobuf-compiler
      - libbullet-dev
      - libgtest-dev
script:
  - ls
  - cd $TRAVIS_BUILD_DIR
  - ls
  - mkdir build && cd build
  - cmake ..
  - make
