//
// Created by rolf on 24-11-19.
//

#ifndef ROBOTEAM_MIMIR_WHEELGROUNDINTERACTION_H
#define ROBOTEAM_MIMIR_WHEELGROUNDINTERACTION_H

enum  bodyType{
    WHEEL=1,
    GROUND=2
};

#endif //ROBOTEAM_MIMIR_WHEELGROUNDINTERACTION_H
